title: Avishek Das
url: "https://avishekdas.net"
#baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Education"
   link: "education.html"
 - name: "Experience"
   link: "experience.html"
 - name: "Publication"
   link: "publication.html"
 - name: "Projects"
   link: "project.html"
 - name: "Skills"
   link: "skills.html"
 - name: "Contact"
   link: "contact.html"
