name: ci:deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    # env:
      # BASEURL: '/' # optional, must start with / but not end with /
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
          bundler-cache: true
      - name: install
        run: gem install bundler && bundle
      - name: build
        run: bundle exec rake build
#       - name: test
#         run: bundle exec rake test
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{secrets.ftp_server}}
          username: ${{secrets.ftp_username}}
          password: ${{secrets.ftp_password}}
          local-dir: ./_site/
          state-name: ./.ftp-deploy-sync-state.json
          server-dir: './' # '/new_portfoio/' # optional subdir, must end in /
